on:
  push:
  pull_request:
name: check
jobs:
  check:
    name: codestyle
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
        with:
          python-version: "3.8.18"
          architecture: "x64"
      - uses: snok/install-poetry@a783c322200f0519c7926aa6faa857c4e23e9263 # v1.4.2
        with:
          version: "1.8.5"
      - run: poetry lock --no-update
      - run: poetry install
      - uses: astral-sh/ruff-action@v4.1.0
        with:
          args: "format --check --diff"
      - uses: astral-sh/ruff-action@v4.1.0
        with:
          args: "check --select E4,E7,E9,F"
      - run: poetry run mypy ./kindle_sdr_cleaner.py
