on:
  push:
  pull_request:
name: check
jobs:
  check:
    name: codestyle
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: "3.8"
          architecture: "x64"
      - uses: snok/install-poetry@v1.4.2
        with:
          version: "1.8.5"
      - run: poetry install
      - run: poetry run black --check .
      - run: poetry run mypy ./kindle_sdr_cleaner.py
